// Every UI export must appear here; visual-coverage.test.ts enforces the inventory.
export const scenarios = {
  vue: {
    buttons: ['GlassButton', 'GlassIconButton'],
    forms: ['GlassField', 'GlassCheckbox', 'GlassRadio', 'GlassSwitch', 'GlassSegmented', 'GlassTabs'],
    select: ['GlassSelect'],
    feedback: ['GlassBadge', 'GlassAlert', 'GlassSpinner', 'GlassProgress', 'GlassSkeleton'],
    containers: ['GlassSurface', 'GlassPanel', 'GlassBar', 'GlassTable'],
    popover: ['GlassPopover', 'GlassMenu'],
    tooltip: ['GlassTooltip'],
    modal: ['GlassModal'],
    'drawer-left': ['GlassDrawer'],
    'drawer-right': ['GlassDrawer'],
    toast: ['GlassToaster'],
    confirm: ['GlassConfirmHost'],
    sidebar: ['ConsoleSidebar'],
    'sidebar-collapsed': ['ConsoleSidebar'],
    palette: ['ConsolePalette'],
    docs: ['DocsLayout'],
    account: ['AccountMenu', 'AccountPrefs'],
    preferences: ['AccountPrefs'],
    products: ['ProductSwitcher'],
    organizations: ['OrgSwitcher'],
    footer: ['SiteFooter'],
    'footer-compact': ['SiteFooter'],
    logo: ['LatereLogoMark'],
    effects: ['GlassSurface'],
  },
  react: {
    buttons: ['GlassButton'],
    forms: ['GlassField', 'GlassCheckbox', 'GlassSegmented', 'GlassSelect'],
    feedback: ['GlassBadge', 'GlassAlert', 'GlassSpinner'],
    containers: ['GlassPanel', 'GlassBar', 'GlassTable'],
    modal: ['GlassModal'],
    sidebar: ['ConsoleSidebar'],
    'sidebar-collapsed': ['ConsoleSidebar'],
    account: ['AccountMenu'],
    footer: ['SiteFooter'],
    'footer-compact': ['SiteFooter'],
    logo: ['LatereLogoMark'],
  },
} as const;

export const mobileScenarios = new Set(['forms', 'select', 'feedback', 'modal', 'drawer-left', 'drawer-right', 'toast', 'confirm', 'sidebar-collapsed', 'palette', 'docs', 'account', 'preferences', 'products', 'footer', 'footer-compact']);
