// Every public visual export participates in both adapters and all four viewport/theme combinations.
const sheets = {
    workspace: ['ConsoleSidebar', 'GlassBar', 'GlassPanel', 'GlassTable'],
    buttons: ['GlassButton', 'GlassIconButton'],
    forms: ['GlassField', 'GlassCheckbox', 'GlassRadio', 'GlassSwitch', 'GlassSegmented', 'GlassTabs'],
    select: ['GlassSelect'],
    feedback: ['GlassBadge', 'GlassAlert', 'GlassSpinner', 'GlassProgress', 'GlassSkeleton'],
    containers: ['GlassSurface', 'GlassPanel', 'GlassBar', 'GlassTable'],
    popover: ['GlassPopover', 'GlassMenu'],
    tooltip: ['GlassTooltip'],
    modal: ['GlassModal'],
    'drawer-left': ['GlassDrawer'],
    'drawer-right': ['GlassDrawer'],
    toast: ['GlassToaster'],
    confirm: ['GlassConfirmHost'],
    sidebar: ['ConsoleSidebar'],
    'sidebar-collapsed': ['ConsoleSidebar'],
    palette: ['ConsolePalette'],
    docs: ['DocsLayout'],
    account: ['AccountMenu', 'AccountPrefs'],
    preferences: ['AccountPrefs'],
    products: ['ProductSwitcher'],
    organizations: ['OrgSwitcher'],
    footer: ['SiteFooter'],
    'footer-compact': ['SiteFooter'],
    logo: ['LatereLogoMark', 'PlatformLogoMark'],
    effects: ['GlassSurface'],
  } as const;
export const scenarios = { vue: sheets, react: sheets } as const;
export const mobileScenarios = new Set<string>(Object.keys(sheets));
