// Every public visual export appears in a sheet, rendered in all four viewport/theme combinations.
export const scenarios = {
    workspace: ['ConsoleSidebar', 'GlassBar', 'GlassPanel', 'GlassTable'],
    buttons: ['GlassButton', 'GlassIconButton'],
    forms: ['GlassField', 'GlassCheckbox', 'GlassRadio', 'GlassSwitch', 'GlassSegmented', 'GlassTabs'],
    select: ['GlassSelect'],
    feedback: ['GlassBadge', 'GlassAlert', 'GlassSpinner', 'GlassProgress', 'GlassSkeleton'],
    containers: ['GlassSurface', 'GlassPanel', 'GlassBar', 'GlassTable'],
    popover: ['GlassPopover', 'GlassMenu'],
    tooltip: ['GlassTooltip'],
    modal: ['GlassModal'],
    'drawer-left': ['GlassDrawer'],
    'drawer-right': ['GlassDrawer'],
    toast: ['GlassToaster'],
    confirm: ['GlassConfirmHost'],
    sidebar: ['ConsoleSidebar'],
    'sidebar-collapsed': ['ConsoleSidebar'],
    palette: ['ConsolePalette'],
    docs: ['DocsLayout'],
    account: ['AccountMenu', 'AccountPrefs'],
    preferences: ['AccountPrefs', 'ThemeMenu', 'LocaleMenu'],
    organizations: ['OrgSwitcher'],
    footer: ['SiteFooter'],
    'footer-compact': ['SiteFooter'],
    logo: ['LatereLogoMark', 'PlatformLogoMark'],
    effects: ['GlassSurface'],
  } as const;
export const mobileScenarios = new Set<string>(Object.keys(scenarios));
